load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "26.3",
    srcs = glob(["*.kt"]),
    actual = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_25",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_25",
    merge_deps = [
        "//touchcontroller/versions/extension/26.3",
        "//touchcontroller/versions/gal/entity/26.3",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/backend/minecraft/item/26.3",
        "//combine/item/data",
        "//game/26.3:game_client",
        "//game/26.3:game_client_libraries",
        "//touchcontroller/common/config/item",
        "//touchcontroller/common/gal/entity",
        "//touchcontroller/common/gal/player",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
