load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "serialization",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/data",
        "//combine/core/paint",
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/data/serialization",
        "//touchcontroller/common/config/item",
        "//touchcontroller/common/config/item/serialization",
        "//touchcontroller/common/config/platform",
        "//touchcontroller/common/config/platform/serialization",
        "//touchcontroller/common/config/preset/builtin/key",
        "//touchcontroller/common/config/preset/builtin/key/serialization",
        "//touchcontroller/common/gal/itemlist",
        "//touchcontroller/common/serialization",
        "@maven//:com_ubertob_kondor_kondor_core",
    ],
)
