load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "property",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/assets",
        "//touchcontroller/resources/texture:texture_set_lib",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/paint",
    ],
)
