load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "text_item",
    srcs = glob(["**/*.kt"]),
    kotlinc_opts = "//intellij_plugin:kotlinc_opts",
    resource_strip_prefix = "intellij_plugin/text_item/resources",
    resources = glob(["resources/**"]),
    deps = [
        "@intellij//:java",
        "@intellij//:kotlin",
        "@intellij//:sdk",
    ],
)
