load("//rule:merge_library.bzl", "kt_merge_library", "merge_library_jar")

kt_merge_library(
    name = "text_item_unmerged",
    srcs = glob(["**/*.kt"]),
    kotlinc_opts = "//intellij_plugin:kotlinc_opts",
    resource_strip_prefix = "intellij_plugin/text_item/resources",
    resources = glob(["resources/**"]),
    deps = [
        "@intellij//:java",
        "@intellij//:kotlin",
        "@intellij//:sdk",
    ],
)

merge_library_jar(
    name = "text_item",
    deps = [":text_item_unmerged"],
)
