load("@rules_java//java:java_binary.bzl", "java_binary")
load("//combine:libraries.bzl", "combine_unified_deps", "combine_unified_neoforge")
load("//combine:properties.bzl", "combine_version")
load("//rule:class_version_test.bzl", "class_version_test")
load("//rule:merge_library.bzl", "kt_merge_library", "merge_library_jar")
load("//rule:unified_jar.bzl", "unified_jar")
load("//rule/neoforge:merge_jij.bzl", "neoforge_merge_jij")
load("//rule/neoforge:mod_toml_jar.bzl", "neoforge_mod_toml_jar")
load("//touchcontroller:libraries.bzl", "touchcontroller_merge_deps", "touchcontroller_unified_deps", "touchcontroller_unified_neoforge")
load("//touchcontroller:properties.bzl", "touchcontroller_authors", "touchcontroller_contributors", "touchcontroller_description", "touchcontroller_homepage", "touchcontroller_issue_tracker", "touchcontroller_license", "touchcontroller_source", "touchcontroller_version")

neoforge_mod_toml_jar(
    name = "neoforge_mod_toml",
    src = "resources/neoforge.mods.toml",
    substitutions = {
        "${version}": touchcontroller_version,
        "${license}": touchcontroller_license,
        "${home_page}": touchcontroller_homepage,
        "${sources_page}": touchcontroller_source,
        "${issue_tracker}": touchcontroller_issue_tracker,
        "${description}": touchcontroller_description,
        "${combine_version}": combine_version,
        "${mod_authors}": ", ".join(touchcontroller_authors),
        "${mod_contributors}": ", ".join(touchcontroller_contributors),
    },
)

kt_merge_library(
    name = "neoforge_unmerged",
    srcs = glob(
        include = [
            "**/*.kt",
            "**/*.java",
        ],
    ),
    javac_opts = "//touchcontroller:javac_opts_jvm_21",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_21",
    merge_deps = [
        "//touchcontroller/versions/extension/1.21.1",
        "//touchcontroller/versions/gal/gameconfig/1.21.1",
        "//touchcontroller/versions/gal/key/1.21.1",
        "//touchcontroller/versions/neoforge/gal/key/1.21.1",
    ],
    merge_only_deps = [
        "//touchcontroller/versions/1.21.1",
        "//touchcontroller/versions/neoforge/gal/1.21.1",
    ],
    resource_jars = [
        ":neoforge_mod_toml",
        "//touchcontroller/resources/texture:icon_jar",
    ],
    resource_strip_prefix = "touchcontroller/versions/neoforge/1.21.1/resources",
    resources = glob(
        include = ["resources/**"],
        exclude = ["resources/neoforge.mods.toml"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//game/1.21.1:game_client_libraries",
        "//game/1.21.1:game_client_neoforge",
    ] + [
        "//combine/backend/minecraft/render/1.21.1",
        "//touchcontroller/buildinfo",
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/holder",
        "//touchcontroller/common/event/block",
        "//touchcontroller/common/event/connection",
        "//touchcontroller/common/event/key",
        "//touchcontroller/common/event/render",
        "//touchcontroller/common/event/tick",
        "//touchcontroller/common/event/window",
        "//touchcontroller/common/gal/key",
        "//touchcontroller/common/layout/data",
        "//touchcontroller/common/model",
        "//touchcontroller/common/platform",
        "//touchcontroller/common/platform/provider",
        "//touchcontroller/common/ui/config/screen",
        "@neoforge_1_21_1//:net_fabricmc_sponge_mixin",
        "@neoforge_1_21_1//:net_neoforged_bus",
        "@neoforge_1_21_1//:net_neoforged_fancymodloader_loader",
        "@neoforge_1_21_1//:net_neoforged_mergetool",
    ],
)

merge_library_jar(
    name = "neoforge",
    aspect_impl_package_suffix = "neoforge.v1_21_1",
    aspects = ["//touchcontroller/common:common_merged"],
    deps = [":neoforge_unmerged"],
)

class_version_test(
    name = "neoforge_class_version",
    class_major = 65,
    jars = [":neoforge"],
    tags = ["class_version"],
)

alias(
    name = "1.21.1",
    actual = "neoforge",
    visibility = ["//touchcontroller:__subpackages__"],
)

unified_jar(
    name = "neoforge_merged",
    merge_deps = touchcontroller_merge_deps,
    neoforge_rules = combine_unified_neoforge | touchcontroller_unified_neoforge | {
        "combine-common": "",
        "combine-theme-blackstone": "",
        "combine-theme-blackstone-atlas": "minecraft: +[1.21.1]",
        "combine-neoforge-1-21-1": "minecraft: +[1.21.1]",
        "touchcontroller-1-21-1-neoforge": "minecraft: +[1.21.1]",
        "touchcontroller-api": "",
        "touchcontroller-common": "",
        "touchcontroller-lang-modern": "minecraft: +[1.21.1]",
        "touchcontroller-texture": "",
        "touchcontroller-texture-atlas": "minecraft: +[1.21.1]",
    },
    deps = combine_unified_deps | touchcontroller_unified_deps | {
        "combine-common": "//combine/backend/minecraft:minecraft_common_standalone",
        "combine-theme-blackstone": "//combine/theme/blackstone:blackstone_common",
        "combine-theme-blackstone-atlas": "//combine/theme/blackstone:blackstone_atlas",
        "combine-neoforge-1-21-1": "//combine/backend/minecraft/neoforge/1.21.1",
        "touchcontroller-1-21-1-neoforge": ":neoforge",
        "touchcontroller-api": "//touchcontroller/api",
        "touchcontroller-common": "//touchcontroller/common:common_merged",
        "touchcontroller-lang-modern": "//touchcontroller/resources/lang:lang",
        "touchcontroller-texture": "//touchcontroller/resources/texture:texture_common",
        "touchcontroller-texture-atlas": "//touchcontroller/resources/texture:texture_atlas",
    },
)

java_binary(
    name = "dev_client",
    srcs = [],
    data = [
        "//game/1.21.1:game_client_assets",
        "//game/1.21.1:game_client_assets_version",
        "//game/1.21.1:game_client_neoforge",
        "//game/1.21.1:game_kotlinforforge",
    ] + [
        ":neoforge_merged",
        "@neoforge_1_21_1//:ignore_list_client",
        "@neoforge_1_21_1//:neoforge_modules",
        "@neoforge_1_21_1//:resources_jar",
    ],
    env = {
        "LANG": "en_US.UTF8",
    },
    jvm_flags = [
        "--add-exports=java.base/sun.security.util=cpw.mods.securejarhandler",
        "--add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming",
        "--add-opens=java.base/java.util.jar=cpw.mods.securejarhandler",
        "--add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler",
        "--add-modules=ALL-MODULE-PATH",
        "-Ddev.launch.version=1.21.1",
        "-Ddev.launch.neoFormVersion=1.21.1-20251209.172050",
        "-Ddev.launch.neoForgeVersion=21.1.218",
        "-Ddev.launch.fmlVersion=4.0.42",
        "-Ddev.launch.legacyFml=true",
        "-Ddev.launch.type=client",
        "-Ddev.launch.ignoreList=$(rlocationpath @neoforge_1_21_1//:ignore_list_client)",
        "-Ddev.launch.assetsVersion=$(rlocationpath //game/1.21.1:game_client_assets_version)",
        "-Ddev.launch.classPath=$(rlocationpath //game/1.21.1:game_client_neoforge)",
        "-Ddev.launch.classPath=$(rlocationpath @neoforge_1_21_1//:resources_jar)",
        "-Ddev.launch.classPath=$(rlocationpath :neoforge_merged)",
        "-Ddev.launch.classPath=$(rlocationpath //game/1.21.1:game_kotlinforforge)",
        "-Xmx4G",
        "START_MODULEPATH",
        "$(rlocationpaths @neoforge_1_21_1//:neoforge_modules)",
        "END_MODULEPATH",
        "--",
        "--launchTarget=forgeclientuserdev",
    ],
    launcher = "//rule/dev_launch_wrapper:launcher",
    main_class = "cpw.mods.bootstraplauncher.BootstrapLauncher",
    runtime_deps = [
        "//game/1.21.1:game_client_libraries",
    ] + [
        "//combine/backend/minecraft",
        "@neoforge_1_21_1//:neoforge_deps",
    ],
)
