modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="touchcontroller_1_21_11"
version="${version}"
displayName="TouchController"
displayURL="${home_page}"
logoFile="assets/touchcontroller/textures/icon.png"
authors="${mod_authors}"
credits="${mod_contributors}"
description="${description}"

[[mixins]]
config="touchcontroller.mixins.json"

[[mixins]]
config="touchcontroller.mixins.neoforge.json"

[[dependencies.touchcontroller_1_21_11]]
modId="minecraft"
mandatory=true
versionRange="[1.21.11]"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="neoforge"
mandatory=true
versionRange="[21.11.13-beta,)"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="combine"
mandatory=true
versionRange="[${combine_version},]"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="touchcontroller"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="touchcontroller_texture_vanilla"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.touchcontroller_1_21_11]]
modId="touchcontroller_lang_modern"
type="required"
ordering="NONE"
side="CLIENT"
