load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "serialization",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//touchcontroller/common/config/layout",
        "//touchcontroller/common/config/layout/serialization",
        "//touchcontroller/common/config/preset",
        "//touchcontroller/common/config/preset/info",
        "//touchcontroller/common/config/preset/info/serialization",
        "@maven//:com_ubertob_kondor_kondor_core",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
