load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "noop-test",
    srcs = ["NoopResolverTest.kt"],
    test_class = "top.fifthlight.pathflow.resolvers.noop.test.NoopResolverTest",
    deps = [
        "//pathflow/data",
        "//pathflow/resolvers/noop",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
        "@maven//:org_jetbrains_kotlin_kotlin_test_junit",
    ],
)
