license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="combine_1_21_10"
version="${version}"
displayName="Combine 1.21.10 implementation"
displayURL="${home_page}"
logoFile="icon.png"
authors="fifth_light"
description="${description}"

[[mixins]]
config="combine.mixins.render.json"

[[accessTransformers]]
file="access_transformer.cfg"

[[dependencies.combine_1_21_10]]
modId="minecraft"
type="required"
versionRange="1.21.10"
ordering="NONE"
side="CLIENT"

[[dependencies.combine_1_21_10]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"
