license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="combine"
version="${version}"
displayName="Combine"
displayURL="${home_page}"
logoFile="icon.png"
authors="fifth_light"
description="${description}"

[[dependencies.combine]]
modId="minecraft"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.combine]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"
