load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "window",
    srcs = glob(["*.kt"]),
    expect = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/data",
        "@maven_blazesdl//:org_lwjgl_lwjgl_sdl",
    ],
)
