license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="touchcontroller_texture_vanilla"
version="${version}"
displayName="${name}"
displayURL="${home_page}"
logoFile="assets/touchcontroller/textures/icon.png"
authors="${authors}"
description='''${description}'''
