load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("//blazesdl:properties.bzl", "blazesdl_api_version")
load("//rule:maven_publish.bzl", "java_export")

expand_template(
    name = "fabric_mod_json",
    out = "fabric.mod.json",
    substitutions = {
        "${version}": blazesdl_api_version,
    },
    template = "resources/fabric.mod.json",
)

expand_template(
    name = "neoforge_mods_toml",
    out = "META-INF/neoforge.mods.toml",
    substitutions = {
        "${version}": blazesdl_api_version,
    },
    template = "resources/neoforge.mods.toml",
)

java_export(
    name = "api",
    srcs = glob(["**/*.java"]),
    coordinates = "top.fifthlight.blazesdl:blazesdl-api:%s" % blazesdl_api_version,
    resource_strip_prefix = "blazesdl/api",
    resources = [
        ":fabric_mod_json",
        ":neoforge_mods_toml",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jspecify_jspecify",
        "@maven_blazesdl//:org_lwjgl_lwjgl_sdl",
    ],
)
