load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "base",
    srcs = glob(["*.kt"]),
    actual = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/control",
        "//touchcontroller/common/control/name",
        "//touchcontroller/common/layout/align",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//:compose",
        "//combine/core/data",
        "//combine/core/layout",
        "//combine/core/modifier",
        "//combine/core/modifier/placement",
        "//combine/core/modifier/scroll",
        "//combine/core/paint",
        "//combine/core/widget/layout",
        "//combine/data",
        "//combine/widget",
        "//touchcontroller/resources/lang:text_binding",
        "//touchcontroller/resources/texture:texture_lib",
        "@maven//:androidx_compose_runtime_runtime_annotation_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
