load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "serialization",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/assets",
        "//touchcontroller/common/assets/serialization",
        "//touchcontroller/common/control",
        "//touchcontroller/common/control/action",
        "//touchcontroller/common/control/action/serialization",
        "//touchcontroller/common/control/property",
        "//touchcontroller/common/control/property/serialization",
        "//touchcontroller/common/control/widget/boat",
        "//touchcontroller/common/control/widget/boat/serialization",
        "//touchcontroller/common/control/widget/custom",
        "//touchcontroller/common/control/widget/custom/serialization",
        "//touchcontroller/common/control/widget/dpad",
        "//touchcontroller/common/control/widget/dpad/serialization",
        "//touchcontroller/common/control/widget/joystick",
        "//touchcontroller/common/control/widget/joystick/serialization",
        "//touchcontroller/common/layout/align",
        "//touchcontroller/common/layout/align/serialization",
        "//touchcontroller/common/serialization",
        "//touchcontroller/common/util/uuid",
        "//touchcontroller/resources/lang:text_binding",
        "//touchcontroller/resources/texture:empty_texture_lib",
        "//touchcontroller/resources/texture:texture_set_lib",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/data",
        "//combine/core/paint",
        "//combine/data",
        "@maven//:com_ubertob_kondor_kondor_core",
    ],
)
