load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("//combine:libraries.bzl", "combine_libraries", "combine_unified_deps", "combine_unified_fabric", "combine_unified_neoforge")
load("//combine:properties.bzl", "combine_description", "combine_home_page", "combine_issue_tracker", "combine_license", "combine_sources_page", "combine_version")
load("//combine/backend/minecraft:libraries.bzl", "combine_common_deps", "combine_fabric_config", "combine_fabric_deps", "combine_neoforge_config", "combine_neoforge_deps")
load("//rule:class_version_test.bzl", "class_version_test")
load("//rule:merge_jar.bzl", "merge_jar")
load("//rule:merge_library.bzl", "merge_library_jar")
load("//rule:unified_jar.bzl", "unified_jar")

merge_library_jar(
    name = "minecraft_unmerged",
    aspect = True,
    aspect_class = "top.fifthlight.combine.AspectProvider",
    visibility = ["//visibility:public"],
    deps = [
        "//combine",
        "//combine/item",
    ],
)

class_version_test(
    name = "minecraft_unmerged_class_version",
    class_major = 52,
    jars = [":minecraft_unmerged"],
    tags = ["class_version"],
)

expand_template(
    name = "fabric_mod_json",
    out = "fabric.mod.json",
    substitutions = {
        "${version}": combine_version,
        "${license}": combine_license,
        "${description}": combine_description,
        "${home_page}": combine_home_page,
        "${sources_page}": combine_sources_page,
        "${issue_tracker}": combine_issue_tracker,
    },
    template = "resources/fabric.mod.json",
)

# Mod ID is combine_common, and need to be wrapped with an outer JAR with mod ID combine
merge_jar(
    name = "minecraft_common",
    resources = {
        ":fabric_mod_json": "combine/backend/minecraft",
        "//combine/backend/minecraft/neoforge:neoforge_mod_toml": "combine/backend/minecraft/neoforge",
        "//combine/resources:icon": ".",
    },
    visibility = ["//visibility:public"],
    deps = [":minecraft_unmerged"],
)

# Mod ID is combine, so can be used standalone or packaged as JIJ in other mods
merge_jar(
    name = "minecraft_common_standalone",
    resources = {
        "//combine/backend/minecraft/fabric:fabric_mod_json": "combine/backend/minecraft/fabric",
        "//combine/backend/minecraft/neoforge:neoforge_mod_toml": "combine/backend/minecraft/neoforge",
        "//combine/resources:icon": ".",
    },
    visibility = ["//visibility:public"],
    deps = [":minecraft_unmerged"],
)

unified_jar(
    name = "combine_neoforge_libraries",
    neoforge_rules = combine_unified_neoforge,
    visibility = ["//visibility:public"],
    deps = combine_unified_deps,
)

unified_jar(
    name = "minecraft",
    fabric_deps = combine_fabric_config | combine_unified_fabric,
    fabric_mod_json = "//combine/backend/minecraft/fabric:fabric_mod_json",
    neoforge_mod_toml = "//combine/backend/minecraft/neoforge:neoforge_mod_toml",
    neoforge_rules = combine_neoforge_config | combine_unified_neoforge,
    resources = {
        "//combine/resources:icon": ".",
    },
    visibility = ["//visibility:public"],
    deps = combine_fabric_deps | combine_common_deps | combine_neoforge_deps | combine_unified_deps,
)

class_version_test(
    name = "libraries_class_version",
    class_major = 52,
    jars = combine_libraries,
    tags = ["class_version"],
)
