license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="combine_26_1"
version="${version}"
displayName="Combine 26.1 implementation"
displayURL="${home_page}"
logoFile="icon.png"
authors="fifth_light"
description="${description}"

[[mixins]]
config="combine.mixins.render.json"

[[accessTransformers]]
file="access_transformer.cfg"

[[dependencies.combine_26_1]]
modId="minecraft"
type="required"
versionRange="26.1"
ordering="NONE"
side="CLIENT"

[[dependencies.combine_26_1]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"
