load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "unified_jar",
    srcs = glob(["*.java"]),
    resource_strip_prefix = "rule/mergetool/plugin/unified_jar/resources",
    resources = glob(["resources/**"]),
    visibility = ["//rule/mergetool:__pkg__"],
    deps = [
        "//multijar/common",
        "//rule/mergetool/api",
        "//rule/mergetool/plugin/jar_in_jar",
    ],
)
