load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "builtin",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/assets",
        "//touchcontroller/common/control",
        "//touchcontroller/common/control/action",
        "//touchcontroller/common/control/name",
        "//touchcontroller/common/control/texture",
        "//touchcontroller/common/control/widget/boat",
        "//touchcontroller/common/control/widget/custom",
        "//touchcontroller/common/control/widget/dpad",
        "//touchcontroller/common/control/widget/joystick",
        "//touchcontroller/common/gal/key",
        "//touchcontroller/common/layout/align",
        "//touchcontroller/common/util/registry",
        "//touchcontroller/resources/lang:text_binding",
        "//touchcontroller/resources/texture:empty_texture_lib",
        "//touchcontroller/resources/texture:texture_set_lib",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/data",
        "//combine/data",
        "//touchcontroller/api",
    ],
)
