load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "preset",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/config/condition",
        "//touchcontroller/common/config/layout",
        "//touchcontroller/common/config/preset/info",
        "//touchcontroller/common/control",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "@maven//:androidx_compose_runtime_runtime_annotation_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
