load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "serialization",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/data",
        "//combine/core/paint",
        "//combine/data",
        "//combine/item/data",
        "@maven//:com_ubertob_kondor_kondor_core",
        "@maven//:com_ubertob_kondor_kondor_outcome",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
