# Regenerate JSON with:
# bazel run //rule/aboutlibraries_generator --                                      \
#     --config "$(realpath touchcontroller/resources/about/libraries.conf)"         \
#     --output "$(realpath touchcontroller/resources/about/aboutlibraries.json)"

central=https://repo1.maven.org/maven2
android=https://dl.google.com/dl/android/maven2

# Compose Runtime
androidx.compose.runtime:runtime-desktop:1.10.3
androidx.compose.runtime:runtime-saveable-desktop:1.10.3

# AndroidX
androidx.collection:collection-jvm:1.6.0
androidx.arch.core:core-common:2.2.0
androidx.savedstate:savedstate-desktop:1.3.3
androidx.savedstate:savedstate-compose-desktop:1.3.3
androidx.lifecycle:lifecycle-common-jvm:2.9.4
androidx.lifecycle:lifecycle-runtime-desktop:2.9.4
androidx.lifecycle:lifecycle-runtime-compose-desktop:2.9.4

# Kotlin
org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.4.0

# Kondor
com.ubertob.kondor:kondor-core:4.1.0
com.ubertob.kondor:kondor-outcome:4.1.0

# Voyager
cafe.adriel.voyager:voyager-core-desktop:1.1.0-beta03
cafe.adriel.voyager:voyager-navigator-desktop:1.1.0-beta03
cafe.adriel.voyager:voyager-screenmodel-desktop:1.1.0-beta03

# Tween Engine
org.mini2Dx:universal-tween-engine:6.3.3
