load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "resources",
    srcs = glob(["*.kt"]),
    actual = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/buildinfo",
        "//touchcontroller/common/about",
        "//touchcontroller/common/about/serialization",
        "//touchcontroller/common/serialization",
    ],
    resource_jars = [
        "//touchcontroller/resources/about",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "@maven//:com_ubertob_kondor_kondor_core",
    ],
)
