name: Release TouchController
on:
  push:
    tags:
      - "touchcontroller-*"

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write
  actions: read
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MSYS_NO_PATHCONV: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Build
        run: |
          bazel build --verbose_failures --config=opt \
            //touchcontroller:update_log \
            //touchcontroller/fabric

      - name: Attest
        uses: actions/attest@v4
        if: matrix.os == "ubuntu-latest"
        with:
          subject-path: |
            bazel-bin/touchcontroller/fabric/fabric.jar

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            bazel-bin/touchcontroller/update_log.md
            bazel-bin/touchcontroller/fabric/fabric.jar

  publish-staging:
    name: Publish to Modrinth Staging
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    env:
      MODRINTH_ID: ${{ vars.TOUCHCONTROLLER_MODRINTH_ID }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts-ubuntu-latest
          path: release

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Publish to Modrinth
        shell: bash
        run: |
          properties="$(python3 <<< "import os; import json; item = {}; exec(open('touchcontroller/properties.bzl').read(), locals = item); print(json.dumps(item))")"
          mod_version="$(jq -r .touchcontroller_version <<< "${properties}")"
          mod_state="$(jq -r .touchcontroller_state <<< "${properties}")"
          bazel run //rule/modrinth_uploader -- \
            --use-token-from-environment \
            --project-id "${MODRINTH_ID}" \
            --version-name "${mod_version}" \
            --version-id "${mod_version}+fabric" \
            --version-type "${mod_state}" \
            --changelog "$(realpath release/bazel-bin/touchcontroller/update_log.md)" \
            --file-name "TouchController-${mod_version}+fabric.jar" \
            "$(realpath release/bazel-bin/touchcontroller/fabric/fabric.jar) \
            $(jq -cr .touchcontroller_fabric_game_versions.[] <<< "${properties}" | sed 's/^/--game-version /' | tr '\n' ' ') \
            --dependency --dependency-project-id P7dR8mSH --dependency-type required \
            --dependency --dependency-project-id Ha28R6CL --dependency-type required \
            --dependency --dependency-project-id mOgUt4GM --dependency-type optional

  publish-production:
    name: Publish to Modrinth Production
    runs-on: ubuntu-latest
    needs: publish-staging
    environment: production
    env:
      MODRINTH_ID: ${{ vars.TOUCHCONTROLLER_MODRINTH_ID }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts-ubuntu-latest
          path: release

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Publish to Modrinth
        shell: bash
        run: |
          properties="$(python3 <<< "import os; import json; item = {}; exec(open('touchcontroller/properties.bzl').read(), locals = item); print(json.dumps(item))")"
          mod_version="$(jq -r .touchcontroller_version <<< "${properties}")"
          mod_state="$(jq -r .touchcontroller_state <<< "${properties}")"
          bazel run //rule/modrinth_uploader -- \
            --use-token-from-environment \
            --project-id "${MODRINTH_ID}" \
            --version-name "${mod_version}" \
            --version-id "${mod_version}+fabric" \
            --version-type "${mod_state}" \
            --changelog "$(realpath release/bazel-bin/touchcontroller/update_log.md)" \
            --file-name "TouchController-${mod_version}+fabric.jar" \
            "$(realpath release/bazel-bin/touchcontroller/fabric/fabric.jar)" \
            $(jq -cr .touchcontroller_fabric_game_versions.[] <<< "${properties}" | sed 's/^/--game-version /' | tr '\n' ' ') \
            --dependency --dependency-project-id P7dR8mSH --dependency-type required \
            --dependency --dependency-project-id Ha28R6CL --dependency-type required \
            --dependency --dependency-project-id mOgUt4GM --dependency-type optional

      - name: Move file and set environment variables
        shell: bash
        run: |
          properties="$(python3 <<< "import os; import json; item = {}; exec(open('touchcontroller/properties.bzl').read(), locals = item); print(json.dumps(item))")"
          mod_version="$(jq -r .touchcontroller_version <<< "${properties}")"
          mod_state="$(jq -r .touchcontroller_state <<< "${properties}")"
          echo "MOD_VERSION=${mod_version}" >> $GITHUB_ENV
          if [[ "$mod_state" == "release" ]]; then
            echo "MOD_PRERELEASE=false" >> $GITHUB_ENV
          else
            echo "MOD_PRERELEASE=true" >> $GITHUB_ENV
          fi
          mv release/bazel-bin/touchcontroller/fabric/fabric.jar "release/TouchController-${mod_version}+fabric.jar"

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          name: TouchController v${{ env.MOD_VERSION }}
          body_path: release/bazel-bin/touchcontroller/update_log.md
          prerelease: ${{ env.MOD_PRERELEASE == 'true' }}
          files: release/TouchController-*+fabric.jar
