license = "LGPL-3.0-or-later"

[[mods]]
modId = "blazesdl"
version = "${version}"
displayName = "BlazeSDL"
description = "Make Minecraft use SDL3 instead of GLFW."
logoFile = "assets/blazesdl/icon.png"
license = "LGPL-3.0-or-later"
authors = "fifth_light"

[[mixins]]
config = "blazesdl.mixins.json"

[[accessTransformers]]
file = "access_transformer.cfg"

[[dependencies.blazesdl]]
modId = "minecraft"
type = "required"
versionRange = "[26.2, 26.3)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blazesdl]]
modId = "ixeris"
type = "incompatible"
versionRange = "[,4.6.2)"
reason = "Ixeris < 4.6.2 has no SDL support."
