modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="combine_1_21_1"
version="${version}"
displayName="Combine 1.21.1 implementation"
displayURL="${home_page}"
logoFile="icon.png"
authors="fifth_light"
description="${description}"

[[mixins]]
config="combine.mixins.render.json"

[[dependencies.combine_1_21_1]]
modId="minecraft"
type="required"
versionRange="1.21.1"
ordering="NONE"
side="CLIENT"

[[dependencies.combine_1_21_1]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"
