load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "26.2",
    srcs = glob(["*.kt"]),
    actual = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_25",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_25",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//game/26.2:game_client",
        "//game/26.2:game_client_libraries",
    ] + [
        "//combine/data",
        "//touchcontroller/common/gal/window",
    ],
)
