load("//rule:merge_library.bzl", "java_merge_library")

java_merge_library(
    name = "26.2",
    srcs = glob(["*.java"]),
    javacopts = ["--release=25"],
    merge_deps = [
        "//touchcontroller/versions/event/26.2",
        "//touchcontroller/versions/extension/26.2",
    ],
    resource_strip_prefix = "touchcontroller/versions/mixin/26.2/resources",
    resources = ["resources/touchcontroller.mixins.json"],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//game/26.2:game_client",
        "//game/26.2:game_client_libraries",
    ] + [
        "//combine/backend/minecraft/item/26.2",
        "//combine/backend/minecraft/render/26.2",
        "//combine/backend/minecraft/text/26.2",
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/holder",
        "//touchcontroller/common/event/render",
        "//touchcontroller/common/model",
        "//touchcontroller/common/ui/config/screen",
        "//touchcontroller/common/util/crosshair",
        "@maven_fabric_26_2//:net_fabricmc_sponge_mixin",
    ],
)
