load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("//combine:libraries.bzl", "combine_fabric_libraries")
load("//combine:properties.bzl", "combine_version")
load("//rule:jar.bzl", "jar")
load("//rule/fabric:merge_jij.bzl", "fabric_merge_jij")
load("//touchcontroller:libraries.bzl", "touchcontroller_fabric_jij_deps", "touchcontroller_fabric_libraries")
load("//touchcontroller:properties.bzl", "touchcontroller_authors", "touchcontroller_contributors", "touchcontroller_description", "touchcontroller_fabric_mod_json_versions", "touchcontroller_homepage", "touchcontroller_issue_tracker", "touchcontroller_license", "touchcontroller_source", "touchcontroller_version")

expand_template(
    name = "fabric_mod_json",
    out = "fabric.mod.json",
    substitutions = {
        "${version}": touchcontroller_version,
        "${license}": touchcontroller_license,
        "${home_page}": touchcontroller_homepage,
        "${sources_page}": touchcontroller_source,
        "${issue_tracker}": touchcontroller_issue_tracker,
        "${description}": touchcontroller_description,
        "${combine_version}": combine_version,
        '"mod_authors_array"': json.encode(touchcontroller_authors),
        '"mod_contributors_array"': json.encode(touchcontroller_contributors),
        '"mod_game_versions_array"': json.encode(touchcontroller_fabric_mod_json_versions),
    },
    template = "resources/fabric.mod.json",
    visibility = ["//touchcontroller:__pkg__"],
)

jar(
    name = "fabric_unmerged",
    resource_paths = {
        ":fabric_mod_json": "fabric.mod.json",
        "//touchcontroller/resources/texture:icon": "assets/touchcontroller/textures/icon.png",
    },
)

fabric_merge_jij(
    name = "fabric",
    input = ":fabric_unmerged",
    visibility = ["//visibility:public"],
    deps = touchcontroller_fabric_jij_deps | combine_fabric_libraries | touchcontroller_fabric_libraries,
)
