load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "26.2",
    srcs = glob(["*.kt"]),
    actual = True,
    javac_opts = "//touchcontroller:javac_opts_jvm_25",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_25",
    merge_deps = [
        "//touchcontroller/versions/gal/player/26.2",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//game/26.2:game_client",
        "//game/26.2:game_client_libraries",
    ] + [
        "//combine/backend/minecraft/item/26.2",
        "//combine/backend/minecraft/text/26.2",
        "//combine/core/data",
        "//combine/item/data",
        "//touchcontroller/common/gal/creativetab",
        "//touchcontroller/common/gal/player",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
