load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "item",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/gal/item",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/item/data",
        "@maven//:androidx_compose_runtime_runtime_annotation_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
    ],
)
