load("//rule:merge_library.bzl", "kt_merge_library", "merge_library_group")

kt_merge_library(
    name = "config",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/item",
        "//touchcontroller/common/config/platform",
        "//touchcontroller/common/config/preset/builtin/key",
        "//touchcontroller/common/gal/itemlist",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//combine/core/paint",
    ],
)

merge_library_group(
    name = "config_group",
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/condition",
        "//touchcontroller/common/config/condition/input",
        "//touchcontroller/common/config/condition/input/serialization",
        "//touchcontroller/common/config/condition/serialization",
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/data/serialization",
        "//touchcontroller/common/config/holder",
        "//touchcontroller/common/config/item",
        "//touchcontroller/common/config/item/serialization",
        "//touchcontroller/common/config/layout",
        "//touchcontroller/common/config/layout/serialization",
        "//touchcontroller/common/config/platform",
        "//touchcontroller/common/config/platform/serialization",
        "//touchcontroller/common/config/preset",
        "//touchcontroller/common/config/preset/builtin",
        "//touchcontroller/common/config/preset/builtin/key",
        "//touchcontroller/common/config/preset/builtin/key/serialization",
        "//touchcontroller/common/config/preset/info",
        "//touchcontroller/common/config/preset/info/serialization",
        "//touchcontroller/common/config/preset/manager",
        "//touchcontroller/common/config/preset/serialization",
        "//touchcontroller/common/config/preset/topbar",
        "//touchcontroller/common/config/serialization",
        "//touchcontroller/common/config/widget",
    ],
)
